config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {home: "home", registrations: "registrations" }

  devise_scope :user do
    root "homes#index"
    resources :users, only:  [:index]
    resources :groups  do
      resources :transactions,  only:  [:index, :new, :create, :show, :destroy]
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :image, presence: true

  has_many :transactions, dependent: :delete_all

  belongs_to :user, class_name: 'User'

  def transaction_count
    transactions.size
  end

  def transaction_sum
    transactions.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[manage edit update destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
    @group = Group.find(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path(@group), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  def destroy
    @group = Group.find(params[:id])
    @group.delete

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :image, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def image(image)
    if image.present?
      image_tag(url_for(image), alt: 'icon', class: 'thumbnail icon-img')
    else
      image_tag('thumb.png', alt: 'icon', class: 'thumbnail icon-img')
    end
  end
end

app/views/groups/_form.html.erb
<section class="container col-10">
  <%= form_with(model: group) do |form| %>
    <% if group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name,  required: true, class: "form-control" %>
    </div>

    <div class="category-box mb-3">
      <%= form.label :icon, class: "unit-label", style: "display: block" %>
      <%= form.file_field :image, required: true %>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="text-center">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="container mb-3 d-flex border">
  <div class="image p-2">
    <%= image(group.image) %>
  </div>
  <div class="flex-fill p-2">
    <div class="d-flex justify-content-between">
      <p><%= group.name %></p>
      <p>$<%= group.transaction_sum %></p>

    </div>
    <p class="text-secondary">Transactions: <%= group.transaction_count %></p>
    <p class="text-secondary"><%= group.created_at.strftime('%d %b %Y') %></p>
  </div>
</div>
</div>

app/views/groups/_groupi.html.erb
<div id="<%= dom_id group %>" class="container mb-3 d-flex border">
  <div class="image p-2">
    <%= image(group.image) %>
  </div>
  <div class="flex-fill p-2">
    <div class="d-flex justify-content-between">
      <p><%= group.name %></p>
      <p>$<%= group.transaction_sum%></p>

    </div>
    <p class="text-secondary">Transactions: <%= group.transaction_count %></p>
    <p class="text-secondary"><%= group.created_at.strftime('%d %b %Y') %></p>
  </div>
</div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <div></div>
    <h3>Categories</h3>
    <%= render "partials/menu"%>
  </div>
</nav>

<section id="groups" class="container-fluid">
  <%= render "partials/alert"%>

  <div class="container mt-5  ">
    <% @groups.each do |group| %>
      <%= link_to group_transactions_path(group), class: "text-decoration-none text-dark" do %>
        <%= render group %>
      <% end %>
    <% end %>
  </div>
</section>

<footer class="mt-auto p-3 border">
  <div class="text-center  border border-white  rounded bg-green">
    <%= link_to "Add Category", new_group_path, class: "text-decoration-none p-2 text-white index-btn" %>
  </div>
</footer>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", groups_path, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>Categories</h3>
    <%= render "partials/menu" %>
  </div>
</nav>

<section id="groups" class="container-fluid">
  <%= render "partials/alert" %>

  <div class="container my-5">
 
    
  <div class="container mb-3 d-flex border">
  <div class="image p-2">
    <%= image(@group.image) %>
  </div>
  <div class="flex-fill p-2">
    <div class="d-flex justify-content-between">
      <p><%= @group.created_at.strftime('%d %b %Y') %></p>
  </div>
</div>
</div>
 
      <div class="text-end mb-3">
        <%= button_to "Delete", @group, method: :delete, class: "btn btn-outline-danger" %>
      </div>
      <%= link_to "Edit this group", edit_group_path(@group) %> |
      <%= link_to "Back to groups", groups_path %>
  

  </div>
</section>

<div>
</div>