config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {home: "home", registrations: "registrations" }

  devise_scope :user do
    root "homes#index"
    resources :users, only:  [:index]
    resources :groups  do
      resources :transactions,  only:  [:index, :new, :create, :show, :destroy]
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :set_group, only: %i[new create edit update destroy]

  # GET /transactions or /transactions.json
  def index
    set_group
    @transactions = Transaction.where(group_id: params[:group_id])
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.group_id = @group.id

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to group_transactions_path(@group), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    set_transaction
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    set_group
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to group_transactions_path, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount, :group_id).merge(user_id: current_user.id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<section class="container col-10">
<%= form_with(url: group_transactions_path, model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class: "form-control"  %>
    </div>

    <div class="mb-3">
      <%= form.label :amount, style: "display: block" %>
      <%= form.text_field :amount, class: "form-control"  %>
    </div>

  <div class="text-center">
    <%= form.submit  class: "btn btn-success" %>
  </div>
<% end %>
</section> 

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="container my-3 py-2 border">
  <div class="col-12 py-2 d-flex justify-content-between">
    <p class="m-0"><%= transaction.name %></p>
    <b class="m-0">$<%= transaction.amount %></b>
  </div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", groups_path, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>Transactions</h3>
    <%= render "partials/menu" %>
  </div>
</nav>

<div id="transactions" class="container-fluid p-0 mt-5">
  <%= render "groups/group", group: @group %>
  <%= render "partials/alert" %>
  <div class="container mt-5  ">
 
  <% @transactions.each do |transaction| %>
    <%= link_to group_transaction_path(transaction.group_id, transaction.id), class: "text-decoration-none text-dark" do %>
      <%= render transaction %>
    <% end %>
  <% end %>
  </div>
</div>

<footer class="mt-auto p-3 border">
  <div class="text-center border border-white rounded">
    <%= link_to "New Transaction", new_group_transaction_path(@group), class: "text-decoration-none p-2 text-white new-btn" %>
  </div>
</footer>

app/views/transactions/new.html.erb
<nav class="navbar p-3 mb-5 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", :back, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>New Transaction</h3>
    <%= render "partials/menu" %>
  </div>
</nav>

<%= render "form", transaction: @transaction, group: @group %>

app/views/transactions/show.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", :back, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>Transaction</h3>
    <%= render "partials/menu" %>
  </div>
</nav>
<div class="container my-5">
  <%= render @transaction %>

  <div class="text-end mb-3">
    <%= button_to "Delete", group_transaction_url(@transaction.group_id, @transaction.id), method: :delete, class: "btn btn-outline-danger" %>
  </div>
</div>